llm:
  use: siliconflow #  siliconflow dmxapi
  siliconflow:
    - api_key: "sk-hrvpfobqslzrgfxunjrjdflttskthedqtsbifmzfqozrtfza"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-varotcommbpttwkmvrcznqgroqewaglrtcnlskyvaabgolim"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-klnyioflaucgizixndytgxrlwhyrconbzajbgtkovsagttha"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-enzbbnvtcnyfsbuawhjgjsiuwdqmxhpinufobjhvtllmhxuy"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-dcimxgrikpskounlgqjikcjyliiseywxtiwpkcexqhorfhjd"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-crhbholxcqldbqimnluhpikfuomfjdcrwydybxczxwvteoxx"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-lylknofeldklwowhtsmjnogzvvhzyktrjjrhfswnznrxruja"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-zeruudoskwllezurejdaqtoautnomiqtphpyofacbnbzmybe"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-vhfwhragmjtribovcmvkvfyyrqvargpqdeqwqcfllateeqtz"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

    - api_key: "sk-xlyeovdljcpoqjhxaswobnagblkaxyomezmxczddkjdtilew"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-32B" # Qwen/Qwen3-32B  #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200

  dmxapi:
    - api_key: "sk-zeBMnqw4L58EseM8nxCRvO4Iqz7kO6rmrxU5hQOmktKCBhOJ"
      api_base: "https://www.dmxapi.cn/v1/chat/completions"
      model: "gpt-5" #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200
    - api_key: "sk-zeBMnqw4L58EseM8nxCRvO4Iqz7kO6rmrxU5hQOmktKCBhOJ"
      api_base: "https://www.dmxapi.cn/v1/chat/completions"
      model: "gpt-5" #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200
    - api_key: "sk-zeBMnqw4L58EseM8nxCRvO4Iqz7kO6rmrxU5hQOmktKCBhOJ"
      api_base: "https://www.dmxapi.cn/v1/chat/completions"
      model: "gpt-5" #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200
    - api_key: "sk-zeBMnqw4L58EseM8nxCRvO4Iqz7kO6rmrxU5hQOmktKCBhOJ"
      api_base: "https://www.dmxapi.cn/v1/chat/completions"
      model: "gpt-5" #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200
    - api_key: "sk-zeBMnqw4L58EseM8nxCRvO4Iqz7kO6rmrxU5hQOmktKCBhOJ"
      api_base: "https://www.dmxapi.cn/v1/chat/completions"
      model: "gpt-5" #deepseek-ai/DeepSeek-V3 "
      temperature: 0.3
      top_p: 0.9
      rate_limit: 200